name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CI: 'true'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create .env file
        run: |
          echo "# Environment created by GitHub Actions" > .env
          echo "VSCE_PAT=dummy-value-for-ci" >> .env
          echo "# Other optional values" >> .env
          echo "TEST_MODE=true" >> .env
      
      - name: Lint
        run: npm run lint
      
      - name: Build
        run: npm run webpack-prod
      
      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Run tests with xvfb
        run: xvfb-run --auto-servernum npm test
      
      - name: Create Package
        run: npm run package
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package
          path: "*.vsix"
          retention-days: 7 