name: Pull Request Validation

on:
  pull_request:
    branches: [ main, master, develop ]
  
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      CI: 'true'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create .env file
        run: |
          echo "# Environment created by GitHub Actions" > .env
          echo "VSCE_PAT=dummy-value-for-ci" >> .env
          echo "# Other optional values" >> .env
          echo "TEST_MODE=true" >> .env
      
      - name: Lint
        run: npm run lint
      
      - name: Build
        run: npm run webpack-prod
      
      - name: Test
        run: npm test
      
      # Optional: Add code coverage reporting
      # - name: Generate Coverage Report
      #   run: npm run test:coverage
      
      # - name: Upload Coverage Report
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }} 